use once_cell::sync::Lazy;
use std::collections::HashMap;

pub static CHANNEL_DICT: Lazy<HashMap<&str, &str>> = Lazy::new(|| {
    HashMap::from([
        // Hololive EN
        ("mori", "MoriCalliope"),
        ("kiara", "TakanashiKiara"),
        ("ina", "NinomaeInanis"),
        ("gura", "GawrGura"),
        ("ame", "WatsonAmelia"),
        ("irys", "IRyS"),
        ("sana", "TsukumoSana"),
        ("fauna", "CeresFauna"),
        ("kronii", "OuroKronii"),
        ("mumei", "NanashiMumei"),
        ("bae", "HakosBaelz"),
        ("shiori", "ShioriNovella"),
        ("nerissa", "NerissaRavencroft"),
        ("biboo", "KosekiBijou"),
        ("fwmc", "FUWAMOCOch"),
        ("gigi", "holoen_gigimurin"),
        ("ceci", "holoen_ceciliaimmergreen"),
        ("raora", "holoen_raorapanthera"),
        ("erb", "holoen_erbloodflame"),
        // Hololive JP
        ("sora", "TokinoSora"),
        ("roboco", "Robocosan"),
        ("azki", "AZKi"),
        ("miko", "SakuraMiko"),
        ("suisei", "HoshimachiSuisei"),
        ("akirose", "AkiRosenthal"),
        ("haachama", "AkaiHaato"),
        ("fbk", "ShirakamiFubuki"),
        ("matsuri", "NatsuiroMatsuri"),
        ("shion", "MurasakiShion"),
        ("ayame", "NakiriAyame"),
        ("choco", "YuzukiChoco"),
        ("subaru", "OozoraSubaru"),
        ("mio", "OokamiMio"),
        ("okayu", "NekomataOkayu"),
        ("korone", "InugamiKorone"),
        ("pekora", "usadapekora"),
        ("flare", "ShiranuiFlare"),
        ("noel", "ShiroganeNoel"),
        ("marine", "HoushouMarine"),
        ("kanata", "AmaneKanata"),
        ("watame", "TsunomakiWatame"),
        ("towa", "TokoyamiTowa"),
        ("luna", "HimemoriLuna"),
        ("lamy", "YukihanaLamy"),
        ("nene", "MomosuzuNene"),
        ("botan", "ShishiroBotan"),
        ("polka", "OmaruPolka"),
        ("laplus", "LaplusDarknesss"),
        ("lui", "TakaneLui"),
        ("koyori", "HakuiKoyori"),
        ("chloe", "SakamataChloe"),
        ("iroha", "kazamairoha"),
        // Hololive ID
        ("risu", "AyundaRisu"),
        ("moona", "MoonaHoshinova"),
        ("iofi", "AiraniIofifteen"),
        ("ollie", "KureijiOllie"),
        ("anya", "AnyaMelfissa"),
        ("reine", "PavoliaReine"),
        ("zeta", "VestiaZeta"),
        ("kaela", "KaelaKovalskia"),
        ("kobo", "KoboKanaeru"),
        // Hololive DEV_IS
        ("ao", "HiodoshiAo"),
        ("kanade", "OtonoseKanade"),
        ("ririka", "IchijouRirika"),
        ("raden", "JuufuuteiRaden"),
        ("hajime", "TodorokiHajime"),
        ("riona", "IsakiRiona"),
        ("niko", "KoganeiNiko"),
        ("su", "MizumiyaSu"),
        ("chihaya", "RindoChihaya"),
        ("vivi", "KikiraraVivi"),
        // Test streams (always live)
        ("test", "TokyoTones"),
    ])
});
